#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$climate = new League\CLImate\CLImate;

$climate->extend('Highlight');

$climate->arguments->add([
    'user' => [
        'prefix'       => 'url',
        'description'  => 'Url to parse',
    ],
		'iterations' => [
			 'prefix'      => 'i',
			 'longPrefix'  => 'iterations',
			 'description' => 'Number of iterations',
			 'castTo'      => 'int',
	 ],
    'verbose' => [
        'prefix'      => 'v',
        'longPrefix'  => 'verbose',
        'description' => 'Verbose output',
        'noValue'     => true,
    ],
    'help' => [
        'longPrefix'  => 'help',
        'description' => 'Prints a usage statement',
        'noValue'     => true,
    ],
    'path' => [
        'description' => 'The path to push',
    ],
]);
$climate->arguments->parse();
var_dump($climate->arguments->get('user'));
var_dump($climate->arguments->defined('verbose'));
$climate->description('My CLI Script');
$climate->usage();
